require('local.functions')
require('local.basics')
require('local.plugins')

require('local.theme')
require('local.nvimtree')
require('local.lualine')
require('local.telescope')
require('local.lsp')
require('local.gitsigns')
require('local.keybindings')
